### ISSUE TITLE
Fixed-Wing or Multirotor?

### ISSUE THREAD

**Issue by bernhardpg** [mzahana/px4_pid_tuner#3]
Is this for tuning FW vehicles, MR vehicles or both?

**Comment by mzahana** [comment]
Hi @bernhardpg . It does not really matter. It's agnostic to the vehicle (or system) type.

**Comment by bernhardpg** [comment]
That is great. I will attempt to gather some flight data tomorrow to use with this tool. Do you have any recommendations for what kind of flights are best suited for this?

**Comment by mzahana** [comment]
@bernhardpg Sorry for the super late reply. I rarely check/maintain this package.
In general, you need to excite the system modes in the desired axes in order to get good enough data for system identification.
